<?php 
    $this->setTitle('Accueil Boulanger'); 
    $this->setDesc('Page d\'accueil du site');
?>

                <div class="col-md-7" style="background-color: #999">
                    <p>&nbsp;</p>
                </div>
                <div class="col-md-5" style="background-color: #888">
                    <div class="row">
                        <div class="col-md-6" style="background-color: #555">
                            <p>&nbsp;</p>
                        </div>
                        <div class="col-md-6" style="background-color: #333">
                            <p>&nbsp;</p>
                        </div>
                    </div>
                </div>